### ISSUE TITLE
Show progress of the startup on the WebUI

### ISSUE THREAD

**Issue by kelsos** [raiden-network/webui#147] opened 2019-08-29 11:50 UTC
The original problem is described here https://github.com/raiden-network/raiden/issues/4681

This is a followup issue about exposing the startup progress information provided by Raiden to the WebUI.

**Comment by manuelwedler** [comment] 2019-10-08 16:12
Showing the startup progress would make it necessary to make the WebUI available through the Raiden API before the synchronization process is done. At the moment the API is available just after this process.

**Comment by manuelwedler** [comment] 2020-04-17 15:38
duplicate of  #341

**Closed by manuelwedler** 2020-04-17 15:38 UTC
Labels: enhancement
