### ISSUE TITLE
Contacts disappeared from WebUI

### ISSUE THREAD

**Issue by istankovic** [raiden-network/webui#636] opened 2021-05-28 11:35 UTC
During mainnet testing of 2.0.0, I created several contacts, did a bunch of transfers and restarted the Raiden node several times.
At some point I started the node again and noticed that all the contacts disappeared, except for one.

## System:
 - OS: Archlinux
 - Firefox 88.0.1
 - Raiden 2.0.0a2
 - WebUI 1.2.1

**Comment by manuelwedler** [comment] 2021-05-31 08:29
Did you run it on the same port? The contacts are tied to the domain. Could you check what is in the local storage of your browser?

**Comment by istankovic** [comment] 2021-05-31 11:22
Hm, it seems the contacts are back now. Don't know what happenede, but they were definitely not there before. Also, @netcriptus had the same issue.

How can I check the local storage?

**Comment by manuelwedler** [comment] 2021-05-31 11:37
Open the brower's dev tools and from there you can access it. On Firefox it is Storage -> Local Storage.

Hm, the only thing I can imagine is that when you run it on a different port you don't have access to the local storage of the first port.

**Comment by istankovic** [comment] 2021-05-31 13:56
I'm pretty sure the port did not change, however, my local storage does not have anything related to the WebUI, as far as I can tell.

**Comment by manuelwedler** [comment] 2021-06-03 08:44
Closing, because we are not able to reproduce this issue.

**Closed by manuelwedler** 2021-06-03 08:44 UTC
Labels: bug
